__description__ = "Tool to move symbols around in Python."
__license__ = "TBD"
__uri__ = "https://github.com/benchling/move-symbol"
__version__ = "0.0.1"
__author__ = "Benchling Eng"
__email__ = "eng@benchling.com"
